#include <iostream>
#include <string>
#include <vector>
using namespace std;




enum MessageType : int
{
	//SIGN OUT
	CLIENT_SIGN_OUT = 201,

	//SIGN IN
	CLIENT_SIGN_IN = 200,
	SERVER_SIGN_IN_SUCCESS = 1020,
	SERVER_SIGN_IN_WRONG_DETAILS = 1021,
	SERVER_SIGN_IN_ALREADY_CONNECTED = 1022,
	
	//SIGN UP
	CLIENT_SIGN_UP = 203,
	SERVER_SIGN_UP_SUCCESS = 1040,
	SERVER_SIGN_UP_PASS_ILLEGAL = 1041,
	SERVER_SIGN_UP_USER_EXISTS = 1042,
	SERVER_SIGN_UP_USER_ILLEGAL = 1043,
	SERVER_SIGN_UP_OTHER = 1044,

	//EXIT
	CLIENT_APP_EXIT = 299,

	//port
	PORT = 8820,
	IFACE = 0
};
